### ISSUE TITLE
build-ci fails

### ISSUE THREAD

**Issue by RobTillaart** [RobTillaart/SHT31_SWW#2]
```
Build shared library with g++ for uno... 
/opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:459:in `block (2 levels) in perform_unit_tests': undefined method `failure_count=' for #<ArduinoCI::Logger:0x000055f3106c32a8> (NoMethodError)
Did you mean?  failure_count
	from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:4[57](https://github.com/RobTillaart/SHT31_SWW/actions/runs/5611069954/jobs/10266897664?pr=1#step:4:58):in `each'
	from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:457:in `block in perform_unit_tests'
    
	from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:455:in `each'
	from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:455:in `perform_unit_tests'
    Last command:  $ g++ -std=c++0x -shared -fPIC -Wl,-undefined,dynamic_lookup -o /home/runner/work/SHT31_SWW/SHT31_SWW/.arduino_ci/libarduino.so -L/home/runner/work/SHT31_SWW/SHT31_SWW/.arduino_ci -DARDUINO=100 -g -O1 -fno-omit-frame-pointer -fno-optimize-sibling-calls -fsanitize=address -D__AVR__ -D__AVR_ATmega328P__ -DARDUINO_ARCH_AVR -DARDUINO_AVR_UNO -I/opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/arduino_ci-1.6.2/cpp/arduino -I/opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/arduino_ci-1.6.2/cpp/unittest -I/home/runner/Arduino/libraries/SHT31_SWW -I/home/runner/Arduino/libraries/SoftwareWire -I/home/runner/Arduino/libraries/SHT31 /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/arduino_ci-1.6.2/cpp/arduino/Arduino.cpp /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/arduino_ci-1.6.2/cpp/arduino/Godmode.cpp /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/arduino_ci-1.6.2/cpp/arduino/stdlib.cpp /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/arduino_ci-1.6.2/cpp/unittest/ArduinoUnitTests.cpp /home/runner/Arduino/libraries/SHT31_SWW/SHT31_SWW.cpp /home/runner/Arduino/libraries/SoftwareWire/SoftwareWire.cpp /home/runner/Arduino/libraries/SHT31/SHT31.cpp
    
    /home/runner/Arduino/libraries/SoftwareWire/SoftwareWire.cpp: In constructor ‘SoftwareWire::SoftwareWire(uint8_t, uint8_t, boolean, boolean)’:
    /home/runner/Arduino/libraries/SoftwareWire/SoftwareWire.cpp:132:18: error: ‘portModeRegister’ was not declared in this scope; did you mean ‘portInputRegister’?
      132 |   _sdaDirReg   = portModeRegister(port);
          |                  ^~~~~~~~~~~~~~~~
          |                  portInputRegister
    /home/runner/Arduino/libraries/SoftwareWire/SoftwareWire.cpp: In member function ‘void SoftwareWire::printStatus(Print&)’:
    /home/runner/Arduino/libraries/SoftwareWire/SoftwareWire.cpp:523:16: error: cast from ‘volatile uint8_t*’ {aka ‘volatile unsigned char*’} to ‘uint16_t’ {aka ‘short unsigned int’} loses precision [-fpermissive]
      523 |   Ser.println( (uint16_t) _sdaPortReg, HEX);
          |                ^~~~~~~~~~~~~~~~~~~~~~
    /home/runner/Arduino/libraries/SoftwareWire/SoftwareWire.cpp:525:16: error: cast from ‘volatile uint8_t*’ {aka ‘volatile unsigned char*’} to ‘uint16_t’ {aka ‘short unsigned int’} loses precision [-fpermissive]
      525 |   Ser.println( (uint16_t) _sclPortReg, HEX);
          |                ^~~~~~~~~~~~~~~~~~~~~~
	from /opt/hostedtoolcache/Ruby/2.6.10/x64/lib/ruby/gems/2.6.0/gems/arduino_ci-1.6.2/exe/arduino_ci.rb:[60](https://github.com/RobTillaart/SHT31_SWW/actions/runs/5611069954/jobs/10266897664?pr=1#step:4:61)8:in `<top (required)>'
	from /opt/hostedtoolcache/Ruby/2.6.10/x[64](https://github.com/RobTillaart/SHT31_SWW/actions/runs/5611069954/jobs/10266897664?pr=1#step:4:65)/bin/arduino_ci.rb:23:in `load'
	from /opt/hostedtoolcache/Ruby/2.6.10/x64/bin/arduino_ci.rb:23:in `<main>'
    /home/runner/Arduino/libraries/SoftwareWire/SoftwareWire.cpp:527:16: error: cast from ‘volatile uint8_t*’ {aka ‘volatile unsigned char*’} to ‘uint16_t’ {aka ‘short unsigned int’} loses precision [-fpermissive]
      527 |   Ser.println( (uint16_t) _sdaDirReg, HEX);
          |                ^~~~~~~~~~~~~~~~~~~~~
    /home/runner/Arduino/libraries/SoftwareWire/SoftwareWire.cpp:529:16: error: cast from ‘volatile uint8_t*’ {aka ‘volatile unsigned char*’} to ‘uint16_t’ {aka ‘short unsigned int’} loses precision [-fpermissive]
      529 |   Ser.println( (uint16_t) _sclDirReg, HEX);
          |                ^~~~~~~~~~~~~~~~~~~~~
    /home/runner/Arduino/libraries/SoftwareWire/SoftwareWire.cpp:531:16: error: cast from ‘volatile uint8_t*’ {aka ‘volatile unsigned char*’} to ‘uint16_t’ {aka ‘short unsigned int’} loses precision [-fpermissive]
      531 |   Ser.println( (uint16_t) _sdaPinReg, HEX);
          |                ^~~~~~~~~~~~~~~~~~~~~
    /home/runner/Arduino/libraries/SoftwareWire/SoftwareWire.cpp:533:16: error: cast from ‘volatile uint8_t*’ {aka ‘volatile unsigned char*’} to ‘uint16_t’ {aka ‘short unsigned int’} loses precision [-fpermissive]
      533 |   Ser.println( (uint16_t) _sclPinReg, HEX);
          |                ^~~~~~~~~~~~~~~~~~~~~
...Build shared library with g++ for uno                                       ✗
Error: Process completed with exit code 1.
```

**Comment by RobTillaart** [comment]
Sketches compile for UNO with 1.8.19

think this is very low prio

**Comment by RobTillaart** [comment]
https://github.com/RobTillaart/SHT31_SW/tree/SoftwareWire-version-0.2.0-%3D%3D-AVR-only

**Comment by RobTillaart** [comment]
Won't fix so no reason to keep it open.
